name: Build Linux

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Linux amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      - name: Build
        run: |
          mkdir -p build
          go build -o build/openlist-linux-amd64 -ldflags="-w -s" -tags=jsoniter .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openlist-linux-amd64
          path: build/openlist-linux-amd64
          retention-days: 1
